compressionLevel: mixed

enableGlobalCache: false

enableStrictSsl: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard
  - code: YN0018
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com/"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
